# Ensures code is formatted correctly before being checked-in
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
        verbose: false
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier

  - repo: https://github.com/petalmd/git-crypt-pre-commit
    rev: "v0.1" # Use the revision rev you want to point at
    hooks:
      - id: git-crypt
