- defaults:
    link:
      relink: true

- clean: ["~"]

- link:
    ~/.bashrc: bashrc
    ~/.zshrc: zshrc
    ~/.config/nvim: nvim

- shell:
    - [git submodule update --init --recursive, Installing submodules]
